# Generated by Django 4.2.21 on 2025-05-29 11:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habits',
            new_name='Habit',
        ),
    ]
